namespace TASVideos.MovieParsers;

internal class SystemCodes
{
	public const string AppleII = "appleii";
	public const string Arcade = "arcade";
	public const string Atari2600 = "a2600";
	public const string Atari7800 = "a7800";
	public const string C64 = "c64";
	public const string Coleco = "coleco";
	public const string Dos = "dos";
	public const string Ds = "ds";
	public const string Dsi = "dsi";
	public const string Fds = "fds";
	public const string Flash = "flash";
	public const string GameBoy = "gb";
	public const string GameCube = "gc";
	public const string Gba = "gba";
	public const string Gbc = "gbc";
	public const string Genesis = "genesis";
	public const string Gg = "gg";
	public const string Intellivision = "intv";
	public const string Linux = "linux";
	public const string Lynx = "lynx";
	public const string Msx = "msx";
	public const string N3ds = "3ds";
	public const string N64 = "N64";
	public const string Ngb = "ngb";
	public const string Nes = "nes";
	public const string Odyssey2 = "o2";
	public const string Pce = "pce";
	public const string PceCd = "pcecd";
	public const string Pcfx = "pcfx";
	public const string Saturn = "saturn";
	public const string SegaCd = "segacd";
	public const string Sg = "sg1000";
	public const string Sgb = "sgb";
	public const string Sgx = "sgx";
	public const string Sms = "sms";
	public const string Snes = "snes";
	public const string Svi = "svi3x8";
	public const string UzeBox = "uzebox";
	public const string VirtualBoy = "vboy";
	public const string Wii = "wii";
	public const string Windows = "windows";
	public const string WSwan = "wswan";
	public const string X32 = "32x";
	public const string Vectrex = "vec";
	public const string ZxSpectrum = "zxs";
}
